<?php

declare(strict_types=1);

namespace Lattice\Lattice\Support\TypeScript;

use Illuminate\Support\Facades\File;

final class AugmentationWriter
{
    public function __construct(
        private readonly PropsTypeGenerator $propsTypeGenerator,
        private readonly ColumnPropsTransformer $columnPropsTransformer,
    ) {}

    /**
     * @param  list<DiscoveredComponent>  $discovered
     */
    public function write(array $discovered, string $output, string $module): void
    {
        $componentEntries = array_filter(
            $discovered,
            static fn (DiscoveredComponent $c): bool => $c->category === 'field' || $c->category === 'component',
        );

        $columnEntries = array_filter(
            $discovered,
            static fn (DiscoveredComponent $c): bool => $c->category === 'column',
        );

        usort(
            $componentEntries,
            fn (DiscoveredComponent $a, DiscoveredComponent $b): int => $a->type <=> $b->type,
        );

        usort(
            $columnEntries,
            fn (DiscoveredComponent $a, DiscoveredComponent $b): int => $a->type <=> $b->type,
        );

        $componentLines = [];
        foreach ($componentEntries as $component) {
            $propsType = $this->propsTypeGenerator->forClass($component->class);
            $indented = $this->indent($propsType, 4);
            $componentLines[] = sprintf('    "%s": %s;', $component->type, $indented);
        }

        $columnLines = [];
        foreach ($columnEntries as $column) {
            $propsType = $this->columnPropsTransformer->forClass($column->class);
            $indented = $this->indent($propsType, 4);
            $columnLines[] = sprintf('    "%s": %s;', $column->type, $indented);
        }

        $componentBody = $componentLines === [] ? '' : "\n".implode("\n", $componentLines)."\n  ";
        $columnBody = $columnLines === [] ? '' : "\n".implode("\n", $columnLines)."\n  ";

        $interfaceLines = [
            '  interface ComponentProps {',
            '  '.$componentBody,
            '  }',
        ];

        if ($columnLines !== []) {
            $interfaceLines[] = '  interface ColumnProps {';
            $interfaceLines[] = '  '.$columnBody;
            $interfaceLines[] = '  }';
        }

        $content = implode("\n", [
            '// This file is generated by `php artisan lattice:typescript`. Do not edit.',
            sprintf('declare module "%s" {', $module),
            implode("\n", $interfaceLines),
            '}',
            '',
            'export {};',
            '',
        ]);

        File::ensureDirectoryExists(dirname($output));
        File::put($output, $content);
    }

    /** Indent every line except the first by $spaces, preserving blank lines. */
    private function indent(string $type, int $spaces): string
    {
        if (! str_contains($type, "\n")) {
            return $type;
        }

        $pad = str_repeat(' ', $spaces);
        $lines = explode("\n", $type);

        $indented = array_map(
            static fn (string $line, int $i): string => ($i === 0 || trim($line) === '') ? $line : $pad.$line,
            $lines,
            array_keys($lines),
        );

        return implode("\n", $indented);
    }
}
