<?php

declare(strict_types=1);

namespace Lattice\Lattice\Support\TypeScript;

use Spatie\TypeScriptTransformer\Actions\ResolveImportsAndResolvedReferenceMapAction;
use Spatie\TypeScriptTransformer\Collections\TransformedCollection;
use Spatie\TypeScriptTransformer\Data\ModuleImportResolvedReference;
use Spatie\TypeScriptTransformer\Data\WriteableFile;
use Spatie\TypeScriptTransformer\Data\WritingContext;
use Spatie\TypeScriptTransformer\References\PhpClassReference;
use Spatie\TypeScriptTransformer\Transformed\Transformed;
use Spatie\TypeScriptTransformer\TypeScriptNodes\TypeScriptAlias;
use Spatie\TypeScriptTransformer\Writers\Writer;

/**
 * Writes the discovered components as a TypeScript module augmentation, keying each
 * transformed prop body by its wire type under the `ComponentProps` / `ColumnProps`
 * interfaces an app's `@lattice-php/lattice` module exposes.
 */
final class AugmentationWriter implements Writer
{
    /**
     * @param  array<class-string, array{0: string, 1: 'component'|'field'|'column'}>  $components  FQCN => [wire type, category]
     */
    public function __construct(
        private readonly array $components,
        private readonly string $module,
        private readonly string $path,
    ) {}

    public function output(array $transformed, TransformedCollection $transformedCollection): array
    {
        [, $resolvedReferenceMap] = (new ResolveImportsAndResolvedReferenceMapAction)->execute(
            $this->path,
            $transformed,
            $transformedCollection,
        );

        $context = new WritingContext($resolvedReferenceMap);

        $componentEntries = [];
        $columnEntries = [];

        foreach ($transformed as $item) {
            $reference = $item->getReference();
            $node = $item->getNode();

            if (! $reference instanceof PhpClassReference || ! $node instanceof TypeScriptAlias) {
                continue;
            }

            $class = $reference->phpClassNode->getName();

            if (! isset($this->components[$class])) {
                continue;
            }

            [$type, $category] = $this->components[$class];
            $entry = sprintf('    "%s": %s;', $type, $node->type->write($context));

            if ($category === 'column') {
                $columnEntries[$type] = $entry;
            } else {
                $componentEntries[$type] = $entry;
            }
        }

        return [new WriteableFile($this->path, self::render($this->module, $componentEntries, $columnEntries))];
    }

    public function resolveReference(Transformed $transformed): ModuleImportResolvedReference
    {
        return new ModuleImportResolvedReference($transformed->getName(), $this->path);
    }

    /**
     * @param  array<string, string>  $componentEntries  wire type => `"type": <body>;` line
     * @param  array<string, string>  $columnEntries
     */
    public static function render(string $module, array $componentEntries, array $columnEntries): string
    {
        ksort($componentEntries);
        ksort($columnEntries);

        $interfaces = [self::interface('ComponentProps', $componentEntries)];

        if ($columnEntries !== []) {
            $interfaces[] = self::interface('ColumnProps', $columnEntries);
        }

        return implode("\n", [
            '// This file is generated by `php artisan lattice:typescript`. Do not edit.',
            sprintf('declare module "%s" {', $module),
            implode("\n", $interfaces),
            '}',
            '',
            'export {};',
            '',
        ]);
    }

    /**
     * @param  array<string, string>  $entries
     */
    private static function interface(string $name, array $entries): string
    {
        if ($entries === []) {
            return sprintf('  interface %s {}', $name);
        }

        return sprintf("  interface %s {\n%s\n  }", $name, implode("\n", $entries));
    }
}
