codecov:
  notify:
    # vitest + vitest-browser + pest shards 1/2 + pest-browser shards 1/2
    after_n_builds: 6

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
      javascript:
        target: 90%
        threshold: 1%
        flags:
          - vitest
          - vitest-browser
        paths:
          - packages/
    patch:
      default:
        target: 80%
        threshold: 1%
      javascript:
        target: 80%
        threshold: 1%
        flags:
          - vitest
          - vitest-browser
        paths:
          - packages/

flags:
  vitest:
    paths:
      - packages/
  vitest-browser:
    paths:
      - packages/

comment:
  after_n_builds: 6
  require_changes: false
  hide_project_coverage: false

bundle_analysis:
  status: informational
