<?php

declare(strict_types=1);

namespace Lattice\Lattice\Core\Enums;

// Generated by @lattice-php/vite-svg-sprite. Do not edit.
enum Icon: string
{
    case AlignCenter = 'align-center';
    case AlignJustify = 'align-justify';
    case AlignLeft = 'align-left';
    case AlignRight = 'align-right';
    case ArrowDown = 'arrow-down';
    case ArrowUp = 'arrow-up';
    case Bold = 'bold';
    case Check = 'check';
    case ChevronDown = 'chevron-down';
    case ChevronRight = 'chevron-right';
    case ChevronsUpDown = 'chevrons-up-down';
    case CircleAlert = 'circle-alert';
    case CircleCheck = 'circle-check';
    case CircleHelp = 'circle-help';
    case CircleX = 'circle-x';
    case Code = 'code';
    case Columns3 = 'columns-3';
    case Copy = 'copy';
    case ExternalLink = 'external-link';
    case Eye = 'eye';
    case EyeOff = 'eye-off';
    case Filter = 'filter';
    case Heading1 = 'heading-1';
    case Heading2 = 'heading-2';
    case Heading3 = 'heading-3';
    case Highlighter = 'highlighter';
    case Info = 'info';
    case Italic = 'italic';
    case LayoutDashboard = 'layout-dashboard';
    case Link = 'link';
    case List = 'list';
    case ListOrdered = 'list-ordered';
    case Loader2 = 'loader-2';
    case Minus = 'minus';
    case MoreHorizontal = 'more-horizontal';
    case Package = 'package';
    case PanelLeft = 'panel-left';
    case Pencil = 'pencil';
    case PencilLine = 'pencil-line';
    case Plus = 'plus';
    case Quote = 'quote';
    case Receipt = 'receipt';
    case RotateCcw = 'rotate-ccw';
    case Rows3 = 'rows-3';
    case Search = 'search';
    case Send = 'send';
    case Settings = 'settings';
    case Smile = 'smile';
    case Strikethrough = 'strikethrough';
    case Table = 'table';
    case Trash2 = 'trash-2';
    case Underline = 'underline';
    case Users = 'users';
    case X = 'x';
}
