// ─── Envelope machinery ─────────────────────────────────────────────────────
// Inlined verbatim from src/Support/TypeScript/stubs/envelopes.ts by
// NodeModuleWriter. This is the client-side type calculus the generated shapes
// below plug into — generics, conditional resolution, and the consumer
// augmentation seams have no PHP counterpart to generate from, so the
// generator owns them here and the module stays import-free.

export type NodeProps = Record<string, unknown>;

export type CommonNodeProps = {
  dataBindings?: Record<string, string> | null;
  hideWhenCollapsed?: boolean | null;
};

/**
 * Augmentable map of wire `type` string → props for consumer components. Apps
 * extend it via `declare module "@lattice-php/lattice"` so their custom components
 * gain strong prop types; the entries are generated by `php artisan lattice:typescript`.
 * Built-in components resolve through the generated `ComponentPropsMap` below.
 * Types in neither fall back to a loose bag.
 */
export interface ComponentProps {}

/** The column counterpart of `ComponentProps`. */
export interface ColumnProps {}

/** The filter counterpart of `ComponentProps`. */
export interface FilterProps {}

/** The effect counterpart of `ComponentProps`. */
export interface EffectProps {}

/**
 * Resolves a `type` string to its payload: consumer augmentations (`TAugment`)
 * win over generated built-ins (`TBuiltins`), then a loose fallback. The one
 * resolver behind the component, column, filter and effect maps.
 */
export type ResolveProps<
  TAugment,
  TBuiltins,
  TType extends string,
  TFallback,
> = TType extends keyof TAugment
  ? TAugment[TType]
  : TType extends keyof TBuiltins
    ? TBuiltins[TType]
    : TFallback;

export type ComponentPropsOf<TType extends string> = ResolveProps<
  ComponentProps,
  ComponentPropsMap,
  TType,
  NodeProps
> &
  CommonNodeProps;

/**
 * The loose wire node an unknown/untyped `type` resolves to: the shape every node
 * shares, with a loose `props` bag. The single source of the wire-node shape —
 * `Node` (i.e. `Node<string>`) is this.
 */
type LooseNode = {
  id?: string;
  key?: string;
  type: string;
  props?: NodeProps;
  schema?: Schema;
};

/**
 * Built-in `props` is required, not optional — the wire serializes the full prop
 * object, so reads need no optional chaining. Unknown types fall back to `LooseNode`.
 */
export type Node<TType extends string = string> = string extends TType
  ? LooseNode
  : {
      id?: string;
      key?: string;
      props: ComponentPropsOf<TType>;
      schema?: Schema;
      type: TType;
    };

/**
 * Distributes so `NodeUnionOf<"a" | "b">` is `Node<"a"> | Node<"b">` — a
 * discriminated union where `node.type` narrows `node.props`. Domains build
 * their node union from a generated `…NodeType` string union with this.
 */
export type NodeUnionOf<TTypes extends string> = TTypes extends string ? Node<TTypes> : never;

export type Schema = Node[];

/**
 * The generated `Column` base props (serialized by every column regardless of
 * type) back the fallback, so even an unaugmented custom column keeps its
 * common concerns typed.
 */
export type ColumnPropsOf<TType extends string> = ResolveProps<
  ColumnProps,
  ColumnPropsMap,
  TType,
  Column & Record<string, unknown>
>;

export type CommonColumnProps = Column;

/**
 * A column node, authored and consumed like a field/component: `key`/`type`
 * stay top-level, every common concern (`label`/`width`/`filter`/…) lives in
 * `props` on each generated column type. `schema` is only present for a
 * container column: the bound component nodes rendered per row. The column
 * counterpart of `Node`.
 */
export type ColumnNode<TType extends string = string> = {
  type: TType;
  key: string;
  props: ColumnPropsOf<TType>;
  schema?: Schema;
};

export type FilterPropsOf<TType extends string> = ResolveProps<
  FilterProps,
  FilterPropsMap,
  TType,
  Filter & Record<string, unknown>
>;

/**
 * A dedicated table filter, authored and consumed like a field/component:
 * `key`/`type` stay top-level, `props` carries `label` plus whatever the
 * filter type contributes. `schema` is the bound field(s) rendering the
 * filter's control and is absent when empty. The filter counterpart of
 * `ColumnNode`.
 */
export type FilterNode<TType extends string = string> = {
  type: TType;
  key: string;
  props: FilterPropsOf<TType>;
  schema?: Schema;
};

export type EffectPropsOf<TType extends string> = ResolveProps<
  EffectProps,
  EffectPropsMap,
  TType,
  Record<string, unknown>
>;

/**
 * Deliberate exception to the `XNode` naming: an effect is a `{type, props}`
 * envelope without id/key/schema — it is not a node.
 */
export type EffectOf<TType extends string> = string extends TType
  ? Effect
  : { type: TType; props: EffectPropsOf<TType> };

// ─── Generated shapes ───────────────────────────────────────────────────────
export type Action = {
  confirmation: Confirmation | null;
  endpoint: string | null;
  form: Node<"form"> | null;
  icon: string | null;
  label: string | null;
  lazyForm: boolean;
  method: HttpMethod | null;
  modalSide: Side | null;
  modalWidth: ModalWidth | null;
  ref: string | null;
  variant: ButtonVariant | null;
};
export type ActionGroup = {
  label: string | null;
  orientation: Orientation | null;
  ref: string | null;
};
export type ActionNodeType = "action" | "action.bulk" | "action.group";
export type ActionResult = {
  readonly data: Record<string, unknown>;
  readonly effects: Effect[];
};
export type Affix = {
  readonly icon: string | null;
  readonly text: string | null;
};
export type Align = "center" | "left" | "start" | "stretch";
export type Avatar = {
  name: string | null;
  size: Size;
  src: string | null;
};
export type Badge = {
  label: string;
};
export type BadgeColumn = {
  align: ColumnAlign;
  colors: Record<string | number, Color> | null;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type BooleanColumn = {
  align: ColumnAlign;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type Breadcrumb = {
  readonly href: string;
  readonly title: string;
};
export type Breadcrumbs = Record<string, never>;
export type BrowserToken = {
  readonly accessToken: string;
  readonly audience: string;
  readonly expiresIn: number;
  readonly scopes: string[];
  readonly tokenType: string;
};
export type Builder = {
  addLabel: string | null;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  defaultItems: number;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  layout: RowLayout;
  maxItems: number | null;
  minItems: number | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  reorderable: boolean;
  required: boolean;
  resizableColumns: boolean;
  resizeIndicator: boolean;
  rowActions: RowAction[] | null;
  tooltip: string | null;
  value: unknown;
};
export type BulkAction = {
  confirmation: Confirmation | null;
  endpoint: string | null;
  form: Node<"form"> | null;
  icon: string | null;
  label: string | null;
  lazyForm: boolean;
  method: HttpMethod | null;
  modalSide: Side | null;
  modalWidth: ModalWidth | null;
  ref: string | null;
  variant: ButtonVariant | null;
};
export type Button = {
  action: Node<"action"> | Node<"action.bulk"> | null;
  buttonType: ButtonType;
  effects: Effect[];
  href: string | null;
  icon: string | null;
  label: string | null;
  method: HttpMethod | null;
  variant: ButtonVariant | null;
};
export type ButtonType = "button" | "submit" | "reset";
export type ButtonVariant =
  | "default"
  | "destructive"
  | "ghost"
  | "info"
  | "link"
  | "outline"
  | "secondary"
  | "success";
export type Callout = {
  action: Node | null;
  dismissible: boolean;
  message: string;
  title: string | null;
  variant: Variant;
};
export type Callouts = Record<string, never>;
export type Card = {
  description: string | null;
  title: string | null;
  tooltip: string | null;
};
export type ChannelVisibility = "public" | "private" | "presence";
export type Chart = {
  categoryFormat: NumberFormat | DateFormat | null;
  categoryKey: string | null;
  data: Record<string, unknown>[];
  description: string | null;
  grid: boolean;
  height: number;
  legend: boolean;
  series: ChartSeries[];
  title: string | null;
  tooltip: boolean;
  valueFormat: NumberFormat | null;
  xAxis: boolean;
  yAxis: boolean;
};
export type ChartSeries = {
  readonly color: Color | null;
  readonly dataKey: string;
  readonly innerRadius: string;
  readonly maxValue: number | null;
  readonly name: string;
  readonly nameKey: string | null;
  readonly stackId: string | null;
  readonly type: ChartSeriesType;
};
export type ChartSeriesType = "area" | "bar" | "distribution" | "gauge" | "line" | "pie";
export type ChatBox = {
  fill: boolean;
  historyEndpoint: string | null;
  placeholder: string | null;
  remote: RemoteAccess | null;
  streamEndpoint: string | null;
  title: string | null;
};
export type ChatMessage = {
  readonly id: string;
  readonly parts: Node[];
  readonly role: ChatRole;
};
export type ChatNodeType = "chat.box" | "chat.part.text" | "chat.part.tool-call";
export type ChatRole = "user" | "assistant" | "system";
export type Checkbox = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type Choice = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  options: Option[];
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type CloseModal = {
  readonly modal: string | null;
};
export type Collapsible = {
  collapsed: boolean;
  rememberState: boolean;
  tooltip: string | null;
  trigger: Node[];
};
export type Color = {
  readonly dark: string | null;
  readonly kind: ColorKind;
  readonly value: string;
};
export type ColorKind = "named" | "css";
export type ColorName =
  | "default"
  | "muted"
  | "primary"
  | "success"
  | "info"
  | "warning"
  | "danger"
  | "gray"
  | "red"
  | "orange"
  | "yellow"
  | "green"
  | "blue"
  | "purple";
export type ColorPicker = {
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  palette: string[];
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tooltip: string | null;
  value: unknown;
};
export type Column = {
  align: ColumnAlign;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type ColumnAlign = "start" | "center" | "end";
export type ColumnFilter = {
  readonly clauseOptions: ColumnFilterOption[];
  readonly control: FilterControl | null;
  readonly defaultOperator: Op;
  readonly multiple: boolean;
  readonly operators: Op[];
  readonly options: Option[];
  readonly searchable: boolean;
  readonly type: FilterType;
};
export type ColumnFilterOption = {
  readonly clauses: ColumnFilterOptionClause[];
  readonly label: string;
  readonly value: string;
};
export type ColumnFilterOptionClause = {
  readonly operator: Op;
  readonly value: string;
};
export type ColumnNodeType =
  | "column.badge"
  | "column.boolean"
  | "column.icon"
  | "column.image"
  | "column.money"
  | "column.number"
  | "column.stack"
  | "column.text";
export type ColumnPropsMap = {
  "column.badge": BadgeColumn;
  "column.boolean": BooleanColumn;
  "column.icon": IconColumn;
  "column.image": ImageColumn;
  "column.money": MoneyColumn;
  "column.number": NumberColumn;
  "column.stack": StackColumn;
  "column.text": TextColumn;
};
export type ColumnWidth = "xs" | "sm" | "md" | "lg" | "xl";
export type ComponentPropsMap = {
  action: Action;
  "action.bulk": BulkAction;
  "action.group": ActionGroup;
  avatar: Avatar;
  badge: Badge;
  breadcrumbs: Breadcrumbs;
  button: Button;
  callouts: Callouts;
  card: Card;
  chart: Chart;
  "chat.box": ChatBox;
  "chat.part.text": TextPart;
  "chat.part.tool-call": ToolCallPart;
  collapsible: Collapsible;
  dropdown: Dropdown;
  "field.builder": Builder;
  "field.checkbox": Checkbox;
  "field.choice": Choice;
  "field.color-picker": ColorPicker;
  "field.date-input": DateInput;
  "field.date-time-input": DateTimeInput;
  "field.file-upload": FileUpload;
  "field.hidden-input": HiddenInput;
  "field.number-input": NumberInput;
  "field.otp": OtpInput;
  "field.password-input": PasswordInput;
  "field.repeater": Repeater;
  "field.rich-editor": RichEditor;
  "field.select": Select;
  "field.text-input": TextInput;
  "field.textarea": Textarea;
  "field.time-input": TimeInput;
  "field.toggle": Toggle;
  "floating-panel": FloatingPanel;
  form: Form;
  fragment: Fragment;
  grid: Grid;
  heading: Heading;
  icon: Icon;
  image: Image;
  link: Link;
  menu: Menu;
  "menu-item": MenuItem;
  modal: Modal;
  notifications: Notifications;
  outlet: Outlet;
  progress: Progress;
  "raw-block": RawBlock;
  "remote.data-list": DataList;
  section: Section;
  "segmented-control": SegmentedControl;
  separator: Separator;
  sidebar: Sidebar;
  stack: Stack;
  tab: Tab;
  table: Table;
  tabs: Tabs;
  text: Text;
  tooltip: Tooltip;
  topbar: Topbar;
  wizard: Wizard;
  "wizard-step": WizardStep;
};
export type Condition = {
  readonly field: string;
  readonly operator: Op;
  readonly value: unknown;
};
export type Confirmation = {
  readonly cancelLabel: string | null;
  readonly confirmLabel: string | null;
  readonly description: string | null;
  readonly title: string | null;
};
export type DataList = {
  dataEndpoint: string | null;
  emptyLabel: string | null;
  remote: RemoteAccess | null;
};
export type DateFormat = {
  dateStyle: DateTimeStyle | null;
  kind: string;
  month: string | null;
  timeStyle: DateTimeStyle | null;
  year: string | null;
};
export type DateInput = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  max: string | null;
  min: string | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type DateRangeFilter = {
  label: string | null;
};
export type DateTimeInput = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  convertTimezone: boolean;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  max: string | null;
  min: string | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  step: number | null;
  tabIndex: number | null;
  timezone: string | null;
  tooltip: string | null;
  value: unknown;
};
export type DateTimeStyle = "full" | "long" | "medium" | "short";
export type Download = {
  readonly url: string;
};
export type Dropdown = {
  placement: Placement;
  trigger: Node[];
};
export type EditorBlockquote = Record<string, never>;
export type EditorBold = Record<string, never>;
export type EditorBulletList = Record<string, never>;
export type EditorCode = Record<string, never>;
export type EditorCodeBlock = Record<string, never>;
export type EditorDetails = Record<string, never>;
export type EditorEmoji = {
  emojis: string[];
};
export type EditorExtension = {
  type: string;
  props: Record<string, unknown>;
};
export type EditorExtensionPropsMap = {
  blockquote: EditorBlockquote;
  bold: EditorBold;
  "bullet-list": EditorBulletList;
  code: EditorCode;
  "code-block": EditorCodeBlock;
  details: EditorDetails;
  emoji: EditorEmoji;
  heading: EditorHeading;
  highlight: EditorHighlight;
  "horizontal-rule": EditorHorizontalRule;
  italic: EditorItalic;
  link: EditorLink;
  "ordered-list": EditorOrderedList;
  strike: EditorStrike;
  table: EditorTable;
  "text-align": EditorTextAlign;
  underline: EditorUnderline;
};
export type EditorHeading = {
  levels: number[];
};
export type EditorHighlight = Record<string, never>;
export type EditorHorizontalRule = Record<string, never>;
export type EditorItalic = Record<string, never>;
export type EditorLink = {
  openOnClick: boolean;
  protocols: string[];
};
export type EditorOrderedList = Record<string, never>;
export type EditorStrike = Record<string, never>;
export type EditorTable = {
  cols: number;
  rows: number;
  withHeaderRow: boolean;
};
export type EditorTextAlign = {
  alignments: string[];
};
export type EditorUnderline = Record<string, never>;
export type Effect = {
  type: string;
  props: Record<string, unknown>;
};
export type EffectPropsMap = {
  callout: Callout;
  "close-modal": CloseModal;
  download: Download;
  "locale-change": LocaleChange;
  "open-modal": OpenModal;
  redirect: Redirect;
  "reload-component": ReloadComponent;
  "reload-page": ReloadPage;
  "reset-form": ResetForm;
  toast: Toast;
  "toggle-sidebar": ToggleSidebar;
};
export type FieldConditions = {
  readonly disabled: Condition[];
  readonly readOnly: Condition[];
  readonly required: Condition[];
  readonly visible: Condition[];
};
export type FileUpload = {
  accept: string | null;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  files:
    | {
        key: string;
        name: string;
        url: string | null;
        size: number | null;
        token: string;
      }[]
    | null;
  helperText: string | null;
  image: boolean;
  label: string | null;
  maxFiles: number | null;
  maxSize: number | null;
  multiple: boolean;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  signed: boolean;
  tooltip: string | null;
  value: unknown;
};
export type Filter = {
  label: string | null;
};
export type FilterClause = {
  readonly field: string;
  readonly operator: Op;
  readonly value: string;
};
export type FilterControl =
  | "filter.select"
  | "filter.ternary"
  | "filter.date-range"
  | "filter.toggle";
export type FilterIndicator = {
  readonly filter: string;
  readonly label: string;
  readonly value: string;
};
export type FilterNodeType =
  | "filter.date-range"
  | "filter.select"
  | "filter.ternary"
  | "filter.toggle";
export type FilterPropsMap = {
  "filter.date-range": DateRangeFilter;
  "filter.select": SelectFilter;
  "filter.ternary": TernaryFilter;
  "filter.toggle": ToggleFilter;
};
export type FilterType = "text" | "number" | "date" | "boolean";
export type FloatingPanel = {
  label: string | null;
  offset: number;
  placement: FloatingPlacement;
  trigger: Node[];
};
export type FloatingPlacement = "bottom-end" | "bottom-start" | "top-end" | "top-start";
export type Form = {
  action: string | null;
  errorBag: string | null;
  method: HttpMethod | null;
  precognitive: boolean;
  ref: string | null;
  resetOnError: string[] | boolean | null;
  resetOnSuccess: string[] | boolean | null;
  state: Record<string, unknown>;
  status: string | null;
  submitButton: boolean;
  submitButtons: Node<"button">[] | null;
  submitJustify: Justify | null;
  submitLabel: string | null;
  submitVariant: ButtonVariant | null;
  validationSummaryLabel: string;
  validationTimeout: number | null;
};
export type FormFieldNodeType =
  | "field.builder"
  | "field.checkbox"
  | "field.choice"
  | "field.color-picker"
  | "field.date-input"
  | "field.date-time-input"
  | "field.file-upload"
  | "field.hidden-input"
  | "field.number-input"
  | "field.otp"
  | "field.password-input"
  | "field.repeater"
  | "field.rich-editor"
  | "field.select"
  | "field.text-input"
  | "field.textarea"
  | "field.time-input"
  | "field.toggle"
  | "wizard"
  | "wizard-step";
export type FormNodeType =
  | "field.builder"
  | "field.checkbox"
  | "field.choice"
  | "field.color-picker"
  | "field.date-input"
  | "field.date-time-input"
  | "field.file-upload"
  | "field.hidden-input"
  | "field.number-input"
  | "field.otp"
  | "field.password-input"
  | "field.repeater"
  | "field.rich-editor"
  | "field.select"
  | "field.text-input"
  | "field.textarea"
  | "field.time-input"
  | "field.toggle"
  | "form"
  | "wizard"
  | "wizard-step";
export type Fragment = {
  endpoint: string | null;
  lazy: boolean;
  ref: string | null;
  size: Size;
};
export type FragmentNodeType = "fragment";
export type FragmentResponse = {
  readonly schema: Node[];
};
export type Gap = "none" | "xs" | "sm" | "md" | "lg" | "xl";
export type Grid = {
  columns: number | null;
};
export type Heading = {
  copyable: boolean;
  level: number;
  text: string;
  tooltip: string | null;
};
export type Height = "full" | "screen";
export type HiddenInput = {
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tooltip: string | null;
  value: unknown;
};
export type HttpMethod = import("@inertiajs/core").Method;
export type I18nConfig = {
  readonly enabled: boolean;
  readonly locales: string[];
  readonly preloadLocales: string[];
  readonly saveMissing: boolean;
  readonly timezone: string | null;
};
export type Icon = {
  class: string | null;
  color: Color | null;
  name: string;
  size: Size;
};
export type IconColumn = {
  align: ColumnAlign;
  colors: Record<string | number, Color> | null;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  icon: string | null;
  icons: Record<string | number, string> | null;
  label: string | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type Image = {
  alt: string | null;
  circular: boolean;
  previewable: boolean;
  size: number | null;
  src: string;
};
export type ImageColumn = {
  align: ColumnAlign;
  circular: boolean;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  previewable: boolean;
  size: number | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type Justify = "start" | "center" | "end" | "between" | "around" | "evenly";
export type LabelAction = {
  readonly href: string;
  readonly label: string;
  readonly tabIndex: number | null;
};
export type LayoutNodeType =
  | "breadcrumbs"
  | "callouts"
  | "dropdown"
  | "menu"
  | "menu-item"
  | "outlet"
  | "sidebar"
  | "topbar";
export type Link = {
  action: Node<"action"> | Node<"action.bulk"> | null;
  effects: Effect[];
  href: string | null;
  icon: string | null;
  label: string | null;
  method: HttpMethod | null;
  prefix: Affix | null;
  suffix: Affix | null;
  tabIndex: number | null;
};
export type Listen = {
  readonly channel: string;
  effects: Effect[];
  events: string[];
  readonly visibility: ChannelVisibility;
};
export type LocaleChange = {
  readonly locale: string;
};
export type Menu = Record<string, never>;
export type MenuItem = {
  action: Node<"action"> | Node<"action.bulk"> | null;
  effects: Effect[];
  href: string | null;
  icon: string | null;
  label: string | null;
  method: HttpMethod | null;
  prefix: Affix | null;
  suffix: Affix | null;
};
export type Modal = {
  closeLabel: string;
  description: string | null;
  open: boolean;
  ref: string | null;
  side: Side | null;
  title: string | null;
  width: ModalWidth;
};
export type ModalWidth = "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
export type MoneyColumn = {
  align: ColumnAlign;
  copyable: boolean;
  currency: string | null;
  currencyField: string | null;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  maximumFractionDigits: number | null;
  minimumFractionDigits: number | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type NodeType =
  | "action"
  | "action.bulk"
  | "action.group"
  | "avatar"
  | "badge"
  | "breadcrumbs"
  | "button"
  | "callouts"
  | "card"
  | "chart"
  | "chat.box"
  | "chat.part.text"
  | "chat.part.tool-call"
  | "collapsible"
  | "dropdown"
  | "field.builder"
  | "field.checkbox"
  | "field.choice"
  | "field.color-picker"
  | "field.date-input"
  | "field.date-time-input"
  | "field.file-upload"
  | "field.hidden-input"
  | "field.number-input"
  | "field.otp"
  | "field.password-input"
  | "field.repeater"
  | "field.rich-editor"
  | "field.select"
  | "field.text-input"
  | "field.textarea"
  | "field.time-input"
  | "field.toggle"
  | "floating-panel"
  | "form"
  | "fragment"
  | "grid"
  | "heading"
  | "icon"
  | "image"
  | "link"
  | "menu"
  | "menu-item"
  | "modal"
  | "notifications"
  | "outlet"
  | "progress"
  | "raw-block"
  | "remote.data-list"
  | "section"
  | "segmented-control"
  | "separator"
  | "sidebar"
  | "stack"
  | "tab"
  | "table"
  | "tabs"
  | "text"
  | "tooltip"
  | "topbar"
  | "wizard"
  | "wizard-step";
export type NotificationItem = {
  readonly actions: Node[];
  readonly body: string | null;
  readonly createdAt: string | null;
  readonly href: string | null;
  readonly icon: string | null;
  readonly id: string;
  readonly isRead: boolean;
  readonly title: string | null;
  readonly variant: Variant | null;
};
export type NotificationList = {
  readonly hasMore: boolean;
  readonly notifications: NotificationItem[];
  readonly unreadCount: number;
};
export type NotificationNodeType = "notifications";
export type Notifications = {
  channel: string;
  endpoint: string;
  pollingInterval: number | null;
  slideOut: boolean;
};
export type NumberColumn = {
  align: ColumnAlign;
  compact: boolean;
  copyable: boolean;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  maximumFractionDigits: number | null;
  minimumFractionDigits: number | null;
  sortable: boolean;
  toggleable: boolean;
  unit: NumberFormatUnit | null;
  width: ColumnWidth;
};
export type NumberFormat = {
  currency: string | null;
  kind: string;
  maximumFractionDigits: number | null;
  minimumFractionDigits: number | null;
  notation: string;
  unit: NumberFormatUnit | null;
};
export type NumberFormatUnit =
  | "percent"
  | "kilogram"
  | "gram"
  | "kilometer"
  | "meter"
  | "byte"
  | "kilobyte"
  | "megabyte"
  | "gigabyte"
  | "millisecond"
  | "second"
  | "minute"
  | "hour"
  | "celsius"
  | "fahrenheit";
export type NumberInput = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  max: number | null;
  min: number | null;
  name: string;
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  prefix: Affix | null;
  readOnly: boolean;
  required: boolean;
  slider: boolean;
  step: number | null;
  suffix: Affix | null;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type Op =
  | "contains"
  | "starts_with"
  | "ends_with"
  | "eq"
  | "neq"
  | "gt"
  | "gte"
  | "lt"
  | "lte"
  | "in"
  | "not_in"
  | "before"
  | "after"
  | "empty"
  | "filled";
export type OpenModal = {
  readonly modal: string;
};
export type Option = {
  readonly data: Record<string, unknown> | null;
  readonly label: string;
  readonly value: string;
};
export type Orientation = "horizontal" | "vertical";
export type OtpInput = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  length: number;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tooltip: string | null;
  value: unknown;
};
export type Outlet = Record<string, never>;
export type PageContainer = "centered" | "default";
export type PageLayout = "app" | "auth" | "none";
export type PageLayoutPayload = {
  readonly key: string;
  readonly schema: Node[];
};
export type PagePayload = {
  readonly breadcrumbs: Breadcrumb[];
  readonly container: string;
  readonly layout: PageLayoutPayload | null;
  readonly listeners: Listen[];
  readonly schema: Node[];
  readonly title: string | null;
};
export type PaginationType = "none" | "simple" | "table" | "infinite";
export type PasswordInput = {
  autoComplete: string | null;
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  confirmation: {
    label: string;
    name: string;
    placeholder: string;
  } | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  labelAction: LabelAction | null;
  name: string;
  passwordRules: string | null;
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  prefix: Affix | null;
  readOnly: boolean;
  required: boolean;
  suffix: Affix | null;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type Placement = "top" | "bottom" | "right";
export type Progress = {
  color: Color | null;
  max: number;
  showValue: boolean;
  size: Size;
  value: number;
  variant: ProgressVariant;
};
export type ProgressVariant = "bar" | "circle";
export type RawBlock = {
  html: string;
};
export type Redirect = {
  readonly url: string;
};
export type ReloadComponent = {
  readonly component: string;
};
export type ReloadPage = Record<string, never>;
export type RemoteAccess = {
  readonly audience: string;
  readonly nodeId: string;
  readonly nodeType: string;
  readonly ref: string;
  readonly scopes: string[];
  readonly source: string;
  readonly tokenEndpoint: string;
};
export type RemoteNodeType = "remote.data-list";
export type Repeater = {
  addLabel: string | null;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  defaultItems: number;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  itemLabel: string | null;
  label: string | null;
  layout: RowLayout;
  maxItems: number | null;
  minItems: number | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  reorderable: boolean;
  required: boolean;
  resizableColumns: boolean;
  resizeIndicator: boolean;
  rowActions: RowAction[] | null;
  tooltip: string | null;
  value: unknown;
};
export type ResetForm = {
  readonly form: string | null;
};
export type ResolveResponse = {
  readonly fields: Record<string, Node>;
  readonly prefill: Record<string, unknown>;
  readonly values: Record<string, unknown>;
};
export type RichEditor = {
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  extensions: EditorExtension[];
  helperText: string | null;
  label: string | null;
  name: string;
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tooltip: string | null;
  value: unknown;
};
export type RowAction = {
  destructive: boolean;
  icon: string | null;
  key: string;
  label: string | null;
  type: RowActionType;
};
export type RowActionType = "duplicate" | "remove";
export type RowLayout = "stack" | "table";
export type Section = {
  collapsed: boolean;
  collapsible: boolean;
  description: string | null;
  headerActions: Node[];
  rememberState: boolean;
  title: string | null;
  tooltip: string | null;
};
export type SegmentedControl = {
  emits: string | null;
  label: string | null;
  name: string;
  options: Option[];
  value: string | null;
};
export type Select = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  creatable: boolean;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  emptyLabel: string;
  helperText: string | null;
  label: string | null;
  multiple: boolean;
  name: string;
  options: Option[];
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  searchPlaceholder: string;
  searchable: boolean;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type SelectFilter = {
  label: string | null;
  multiple: boolean;
  options: Option[];
  placeholder: string | null;
  searchable: boolean;
};
export type Separator = {
  orientation: Orientation;
};
export type Side = "start" | "end";
export type Sidebar = {
  collapsible: boolean;
  rememberState: boolean;
};
export type SignedUpload = {
  readonly headers: Record<string, unknown>;
  readonly key: string;
  readonly method: HttpMethod;
  readonly url: string;
};
export type Size = "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl";
export type SortDirection = "asc" | "desc";
export type Stack = {
  align: Align | null;
  direction: StackDirection | null;
  float: Side | null;
  gap: Gap | null;
  height: Height | null;
  justify: Justify | null;
  width: Width | null;
};
export type StackColumn = {
  align: ColumnAlign;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type StackDirection = "row" | "column";
export type Tab = {
  confirm: {
    required: boolean;
    redirectUrl: string;
    timeout: number | null;
  } | null;
  label: string;
  value: string;
};
export type Table = {
  actionsLabel: string | null;
  bulkActions: (Node<"action"> | Node<"action.bulk">)[];
  columns: ColumnNode[];
  emptyLabel: string | null;
  endpoint: string | null;
  filters: FilterNode[];
  layout: string | null;
  lazy: boolean;
  ref: string | null;
  resizableColumns: boolean;
  resizeIndicator: boolean;
  searchable: boolean;
  striped: boolean;
};
export type TableNodeType = "table";
export type TablePagination = {
  readonly currentPage: number | null;
  readonly from: number | null;
  readonly hasMore: boolean;
  readonly lastPage: number | null;
  readonly mode: PaginationType;
  readonly nextPage: number | null;
  readonly perPage: number | null;
  readonly to: number | null;
  readonly total: number | null;
};
export type TableQuery = {
  readonly filters: FilterClause[];
  readonly page: number;
  readonly perPage: number;
  readonly search: string;
  readonly sorts: TableSort[];
  readonly tableFilterIndicators: FilterIndicator[];
  readonly tableFilters: Record<string, Record<string, unknown>>;
};
export type TableResult = {
  readonly data: Record<string, unknown>[];
  readonly pagination: TablePagination | null;
  readonly query: TableQuery;
};
export type TableSort = {
  readonly direction: SortDirection;
  readonly key: string;
};
export type Tabs = {
  activeValue: string;
  alignment: TabsAlignment;
  defaultValue: string | null;
  orientation: Orientation;
  queryKey: string;
};
export type TabsAlignment = "start" | "center" | "end" | "stretch";
export type TernaryFilter = {
  falseLabel: string;
  label: string | null;
  placeholder: string;
  trueLabel: string;
};
export type Text = {
  align: Align | null;
  color: Color | null;
  copyable: boolean;
  size: Size;
  text: string;
};
export type TextColumn = {
  align: ColumnAlign;
  badge: {
    colorKey: string;
  } | null;
  copyable: boolean;
  date: {
    dateStyle: DateTimeStyle | null;
    timeStyle: DateTimeStyle | null;
  } | null;
  filter: ColumnFilter | null;
  hiddenByDefault: boolean;
  label: string | null;
  link: {
    href: string | null;
    external: boolean;
  } | null;
  multiple: string | null;
  sortable: boolean;
  toggleable: boolean;
  width: ColumnWidth;
};
export type TextInput = {
  autoComplete: string | null;
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  copyable: boolean;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  prefix: Affix | null;
  readOnly: boolean;
  required: boolean;
  suffix: Affix | null;
  tabIndex: number | null;
  tooltip: string | null;
  type: string | null;
  value: unknown;
};
export type TextPart = {
  text: string;
};
export type Textarea = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  placeholder: string | null;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  rows: number | null;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type TimeInput = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  max: string | null;
  min: string | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  step: number | null;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type Toast = {
  action: Node | null;
  dismissible: boolean;
  duration: number | null;
  message: Translatable | string;
  persistent: boolean;
  variant: Variant;
};
export type Toggle = {
  autoFocus: boolean;
  columnWidth: ColumnWidth;
  conditions: FieldConditions | null;
  dependsOnAny: boolean;
  dependsOnKeys: string[] | null;
  disabled: boolean;
  editablePrefill: boolean;
  helperText: string | null;
  label: string | null;
  name: string;
  prefillRefreshOn: string[] | null;
  prefillResetOn: string[] | null;
  readOnly: boolean;
  required: boolean;
  tabIndex: number | null;
  tooltip: string | null;
  value: unknown;
};
export type ToggleFilter = {
  label: string | null;
};
export type ToggleSidebar = {
  readonly target: string | null;
};
export type ToolCallPart = {
  args: Record<string, unknown>;
  name: string;
};
export type Tooltip = {
  content: string | null;
  trigger: Node[];
};
export type Topbar = {
  sticky: boolean;
};
export type Translatable = {
  key: string;
  payload: Record<string, string>;
  replacements: Record<string, string | number | boolean>;
};
export type UiNodeType =
  | "avatar"
  | "badge"
  | "button"
  | "card"
  | "chart"
  | "collapsible"
  | "floating-panel"
  | "grid"
  | "heading"
  | "icon"
  | "image"
  | "link"
  | "modal"
  | "progress"
  | "raw-block"
  | "section"
  | "segmented-control"
  | "separator"
  | "stack"
  | "tab"
  | "tabs"
  | "text"
  | "tooltip";
export type UnreadCount = {
  readonly unreadCount: number;
};
export type Variant = "success" | "info" | "warning" | "error";
export type Width = "full" | "auto" | "sm" | "md" | "lg" | "fill";
export type Wizard = {
  orientation: Orientation;
};
export type WizardStep = {
  description: string | null;
  label: string;
  name: string;
};
