import { buildSprite } from "@lattice-php/vite-svg-sprite";
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const packageRoot = path.resolve(import.meta.dirname, "..");
const iconsDir = path.resolve(packageRoot, "../ui/resources/icons");
const outFile = path.resolve(packageRoot, "resources/js/icons/sprite.generated.ts");

const { source, ids } = buildSprite([iconsDir]);

const content = `// Generated by scripts/generate-sprite.mjs from @lattice-php/ui's icon set.
// Regenerate with \`npm run build:sprite --workspace @lattice-php/api-reference\`.
import type { SpriteValue } from "@lattice-php/ui/icons";

export const sprite: SpriteValue = {
  href: "",
  ids: ${JSON.stringify(ids)},
  source:
    ${JSON.stringify(source)},
};
`;

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, content);
// The pre-commit hook formats staged files with oxfmt; format here too so a
// CI regeneration byte-matches the committed file.
execFileSync("npx", ["oxfmt", outFile], { stdio: "ignore" });
console.log(`Wrote ${path.relative(packageRoot, outFile)} (${ids.length} icons)`);
