import type {
  ActionNode,
  ColumnData,
  ColumnFilter,
  ColumnPropsMap,
  ColumnType,
  FilterClause as WireFilterClause,
  Op,
  Table,
  TablePagination,
  TableQuery,
  TableSort,
} from "@lattice-php/lattice/types/generated";

export type { ColumnData, ColumnFilter, ColumnType, TablePagination, TableSort };

export type TableColumn = ColumnData;

export type TableRow = Record<string, unknown>;

/**
 * The wire types `operator` as a free string (validated server-side); on the
 * client a clause always carries a known Op, built from a column's
 * allowed operators.
 */
export type FilterClause = Omit<WireFilterClause, "operator"> & {
  operator: Op;
};

/**
 * The wire `TableQuery` state, with `filters` narrowed to the client `FilterClause`
 * (known `Op` operator) instead of the wire's free-string operator.
 */
export type TableState = Omit<TableQuery, "filters"> & {
  filters: FilterClause[];
};

export type TableResponse = {
  data?: TableRow[];
  pagination?: TablePagination;
  state?: Partial<TableState>;
};

/**
 * The table node as it reaches the client: the generated wire props plus the
 * rows, pagination, and state the server hydrates onto it for the initial render.
 */
export type TableNodeProps = Partial<Omit<Table, "bulkActions">> & {
  bulkActions?: ActionNode[];
  data?: TableRow[];
  pagination?: TablePagination;
  state?: Partial<TableState>;
};

export type TableNode = {
  type: "table";
  id?: string;
  key?: string;
  props?: TableNodeProps;
};

/**
 * Augmentable map of column `type` string → props. Consumer apps extend it via
 * `declare module "@lattice-php/lattice"` so their custom columns gain strong
 * prop types; the entries are generated by `php artisan lattice:typescript`.
 */
export interface ColumnProps {}

// Resolves a built-in column's props from the generated map; `never` when not built-in.
type BuiltInColumnPropsOf<TType extends string> = TType extends keyof ColumnPropsMap
  ? ColumnPropsMap[TType]
  : never;

/**
 * Resolves a column `type` to its props: consumer augmentations (`ColumnProps`)
 * first, then the generated built-ins, then a loose bag.
 */
export type ColumnPropsOf<TType extends string> = TType extends keyof ColumnProps
  ? ColumnProps[TType]
  : [BuiltInColumnPropsOf<TType>] extends [never]
    ? Record<string, unknown> | undefined
    : BuiltInColumnPropsOf<TType>;
