import type { ComponentType as ReactComponentType, ReactNode } from "react";
import type {
  Node as WireNode,
  NodeType,
  Option,
  PageContainer as KnownPageContainer,
} from "@lattice-php/lattice/types/generated";

export type { KnownPageContainer, NodeType, WireNode };

/** Loose props bag for nodes whose `type` is not a generated built-in. */
export type NodeProps = Record<string, unknown>;

export type CommonNodeProps = {
  hideWhenCollapsed?: boolean | null;
};

/** A `{ label, value }` pair used by the choice, select and segmented controls. */
export type { Option };

/**
 * A node whose `type` is not one of the generated built-ins. This is the escape
 * hatch that keeps the renderer open to components registered by consumers.
 */
export type LooseNode<TType extends string = string> = {
  id?: string;
  key?: string;
  props?: NodeProps;
  schema?: Schema;
  type: TType;
};

/**
 * Augmentable map of wire `type` string → props. Consumer apps extend it via
 * `declare module "@lattice-php/lattice"` so their custom components gain strong
 * prop types; the entries are generated by `php artisan lattice:typescript`.
 * Built-in components resolve through the generated `WireNode` union below, so
 * this interface starts empty. Types listed in neither fall back to a loose bag.
 */
export interface ComponentProps {}

// Resolves a built-in node's props from the generated WireNode union; `never` when the type is not a built-in.
type BuiltInPropsOf<TType extends string> = [Extract<WireNode, { type: TType }>] extends [never]
  ? never
  : Extract<WireNode, { type: TType }> extends { props: infer TProps }
    ? TProps
    : never;

/**
 * Resolves a wire `type` to its props: consumer augmentations
 * (`ComponentProps`) first, then generated built-ins, then a loose bag.
 */
export type PropsOf<TType extends string> = TType extends keyof ComponentProps
  ? ComponentProps[TType] & CommonNodeProps
  : [BuiltInPropsOf<TType>] extends [never]
    ? NodeProps & CommonNodeProps
    : BuiltInPropsOf<TType> & CommonNodeProps;

/**
 * Resolves a wire `type` string to its node shape: built-ins narrow to their
 * generated props, unknown types fall back to a loose props bag so custom
 * components still type-check. Built-in `props` is always present — the wire
 * serializes the full prop object, so reads need no optional chaining.
 */
export type NodeOfType<TType extends string = string> = string extends TType
  ? LooseNode
  : {
      id?: string;
      key?: string;
      props: PropsOf<TType>;
      schema?: Schema;
      type: TType;
    };

export type Node<TType extends string = string> = NodeOfType<TType>;

/** An ordered list of component nodes — the content of a page, form, or container. */
export type Schema = Node[];

/** A server-composed layout shell: its key plus a schema containing one Outlet. */
export type LayoutPayload = {
  key: string;
  schema: Schema;
};

export type PagePayload = {
  breadcrumbs: PageBreadcrumb[];
  container: PageContainer;
  layout: LayoutPayload | null;
  schema: Schema;
  title: string | null;
};

export type PageBreadcrumb = {
  href: string;
  title: string;
};

export type PageContainer = KnownPageContainer | (string & {});

export type RendererComponentProps<TType extends string = string> = {
  children: ReactNode;
  node: Node<TType>;
};

export type RendererComponent<TType extends string = string> = ReactComponentType<
  RendererComponentProps<TType>
>;

export type RendererComponentModule<TType extends string = string> = {
  default: RendererComponent<TType>;
};

export type UnknownComponent = ReactComponentType<{
  node: Node;
}>;
