import type { ComponentType as ReactComponentType, ReactNode } from "react";
import type {
  ComponentPropsMap,
  NodeType,
  Option,
  PageContainer as KnownPageContainer,
  WireNode,
} from "@lattice-php/lattice/types/generated";
import type { ListenerPayload } from "@lattice-php/lattice/types/generated";

export type { KnownPageContainer, NodeType, WireNode };

/** Loose props bag for nodes whose `type` is not a generated built-in. */
export type NodeProps = Record<string, unknown>;

export type CommonNodeProps = {
  dataBindings?: Record<string, string> | null;
  hideWhenCollapsed?: boolean | null;
};

/** A `{ label, value }` pair used by the choice, select and segmented controls. */
export type { Option };

/**
 * Augmentable map of wire `type` string → props for consumer components. Apps
 * extend it via `declare module "@lattice-php/lattice"` so their custom components
 * gain strong prop types; the entries are generated by `php artisan lattice:typescript`.
 * Built-in components resolve through the generated `ComponentPropsMap` below, the
 * same way `ColumnProps` augments `ColumnPropsMap`. Types in neither fall back to a
 * loose bag.
 */
export interface ComponentProps {}

/**
 * Resolves a registry `type` string to its payload: consumer augmentations
 * (`TAugment`) first, then generated built-ins (`TBuiltins`), then a loose
 * fallback. Shared by the component, column, chat-part and effect type maps so
 * every extensible kind resolves the same way.
 */
export type ResolveProps<
  TAugment,
  TBuiltins,
  TType extends string,
  TFallback,
> = TType extends keyof TAugment
  ? TAugment[TType]
  : TType extends keyof TBuiltins
    ? TBuiltins[TType]
    : TFallback;

/**
 * Resolves a wire `type` to its props: consumer augmentations
 * (`ComponentProps`) first, then generated built-ins (`ComponentPropsMap`), then a
 * loose bag.
 */
export type PropsOf<TType extends string> = ResolveProps<
  ComponentProps,
  ComponentPropsMap,
  TType,
  NodeProps
> &
  CommonNodeProps;

/**
 * Resolves a wire `type` string to its node shape: built-ins narrow to their
 * generated props, unknown types fall back to the loose `WireNode` so custom
 * components still type-check. Built-in `props` is always present — the wire
 * serializes the full prop object, so reads need no optional chaining.
 */
export type NodeOfType<TType extends string = string> = string extends TType
  ? WireNode
  : {
      id?: string;
      key?: string;
      props: PropsOf<TType>;
      schema?: Schema;
      type: TType;
    };

export type Node<TType extends string = string> = NodeOfType<TType>;

/** An ordered list of component nodes — the content of a page, form, or container. */
export type Schema = Node[];

/** A server-composed layout shell: its key plus a schema containing one Outlet. */
export type LayoutPayload = {
  key: string;
  schema: Schema;
};

/**
 * The page payload the server hydrates onto `lattice` (see PHP `Page::toArray`).
 * Hand-written rather than generated: its `schema`/`layout.schema` are component
 * trees serialized eagerly during the request (to fire side effects before the
 * final encode), so they cannot be derived from a value object as typed `Node[]`.
 */
export type PagePayload = {
  breadcrumbs: PageBreadcrumb[];
  container: PageContainer;
  layout: LayoutPayload | null;
  listeners?: ListenerPayload[];
  schema: Schema;
  title: string | null;
};

export type PageBreadcrumb = {
  href: string;
  title: string;
};

export type PageContainer = KnownPageContainer | (string & {});

export type RendererComponentProps<TType extends string = string> = {
  children: ReactNode;
  node: Node<TType>;
};

export type RendererComponent<TType extends string = string> = ReactComponentType<
  RendererComponentProps<TType>
>;

export type RendererComponentModule<TType extends string = string> = {
  default: RendererComponent<TType>;
};

export type UnknownComponent = ReactComponentType<{
  node: Node;
}>;
