<?php
declare(strict_types=1);

namespace Lattice\Support\TypeScript;

use Lattice\Core\Facades\Lattice;
use Lattice\Core\Support\TypeScript\WireFamily;

/**
 * Renders a TypeScript module augmentation of the app's `@lattice-php/core`
 * module, keying each prop body by wire type under the augmentable interface
 * for its category ({@see WireFamily}).
 */
final readonly class AugmentationWriter
{
    /**
     * @param  array<string, array<string, string>>  $entriesByCategory  category => (wire type => `"type": <body>;` line)
     */
    public static function render(string $module, array $entriesByCategory): string
    {
        $interfaces = [];

        foreach (Lattice::wireFamilies() as $family) {
            $entries = $entriesByCategory[$family->category] ?? [];

            // The component interface is always emitted so the module augmentation is
            // valid even for an app with no custom components; the rest only when populated.
            if ($entries === [] && $family->category !== 'component') {
                continue;
            }

            ksort($entries);
            $interfaces[] = self::interface($family->propsInterface(), $entries);
        }

        return implode("\n", [
            '// This file is generated by `php artisan lattice:typescript`. Do not edit.',
            sprintf('declare module "%s" {', $module),
            implode("\n", $interfaces),
            '}',
            '',
            'export {};',
            '',
        ]);
    }

    /**
     * @param  array<string, string>  $entries
     */
    private static function interface(string $name, array $entries): string
    {
        if ($entries === []) {
            return sprintf('  interface %s {}', $name);
        }

        return sprintf("  interface %s {\n%s\n  }", $name, implode("\n", $entries));
    }
}
